.PHONY: clean All

All:
	@echo "----------Building project:[ Section-16_Challenge - Debug ]----------"
	@cd "Section-16_Challenge" && "$(MAKE)" -f  "Section-16_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section-16_Challenge - Debug ]----------"
	@cd "Section-16_Challenge" && "$(MAKE)" -f  "Section-16_Challenge.mk" clean
