.PHONY: clean All

All:
	@echo "----------Building project:[ Section13_Challenge - Debug ]----------"
	@cd "Section13_Challenge" && "$(MAKE)" -f  "Section13_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section13_Challenge - Debug ]----------"
	@cd "Section13_Challenge" && "$(MAKE)" -f  "Section13_Challenge.mk" clean
