.PHONY: clean All

All:
	@echo "----------Building project:[ InitializeVariables - Debug ]----------"
	@cd "InitializeVariables" && "$(MAKE)" -f  "InitializeVariables.mk"
clean:
	@echo "----------Cleaning project:[ InitializeVariables - Debug ]----------"
	@cd "InitializeVariables" && "$(MAKE)" -f  "InitializeVariables.mk" clean
