.PHONY: clean All

All:
	@echo "----------Building project:[ Section8_Challenge - Debug ]----------"
	@cd "Section8_Challenge" && "$(MAKE)" -f  "Section8_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section8_Challenge - Debug ]----------"
	@cd "Section8_Challenge" && "$(MAKE)" -f  "Section8_Challenge.mk" clean
