.PHONY: clean All

All:
	@echo "----------Building project:[ Section-15_Challenge - Debug ]----------"
	@cd "Section-15_Challenge" && "$(MAKE)" -f  "Section-15_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section-15_Challenge - Debug ]----------"
	@cd "Section-15_Challenge" && "$(MAKE)" -f  "Section-15_Challenge.mk" clean
