.PHONY: clean All

All:
	@echo "----------Building project:[ Section12_Challenge - Debug ]----------"
	@cd "Section12_Challenge" && "$(MAKE)" -f  "Section12_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section12_Challenge - Debug ]----------"
	@cd "Section12_Challenge" && "$(MAKE)" -f  "Section12_Challenge.mk" clean
