.PHONY: clean All

All:
	@echo "----------Building project:[ LinkerErrors - Debug ]----------"
	@cd "LinkerErrors" && "$(MAKE)" -f  "LinkerErrors.mk"
clean:
	@echo "----------Cleaning project:[ LinkerErrors - Debug ]----------"
	@cd "LinkerErrors" && "$(MAKE)" -f  "LinkerErrors.mk" clean
