.PHONY: clean All

All:
	@echo "----------Building project:[ Section14_Challenge-1 - Debug ]----------"
	@cd "Section14-Challenge" && "$(MAKE)" -f  "Section14_Challenge-1.mk"
clean:
	@echo "----------Cleaning project:[ Section14_Challenge-1 - Debug ]----------"
	@cd "Section14-Challenge" && "$(MAKE)" -f  "Section14_Challenge-1.mk" clean
