.PHONY: clean All

All:
	@echo "----------Building project:[ Section-7_Challenge - Debug ]----------"
	@cd "Section-7_Challenge" && "$(MAKE)" -f  "Section-7_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section-7_Challenge - Debug ]----------"
	@cd "Section-7_Challenge" && "$(MAKE)" -f  "Section-7_Challenge.mk" clean
